[package]
name = "restic-browser"
version = "0.3.0"
description = "A restic backup browser GUI"
authors = ["mail@emuell.net"]
license = "MIT"
repository = "https://github.com/emuell/restic-browser"
default-run = "restic-browser"
edition = "2021"
rust-version = "1.60"

[build-dependencies]
tauri-build = { version = "1.4.0", features = [] }

[dependencies]

# common
serde_json = "^1.0"
serde = { version = "^1.0", features = ["derive"] }
log = { version = "^0.4", features = ["max_level_debug", "release_max_level_info"] }
simplelog = { version = "^0.12" }
anyhow = { version = "1.0" }
which = { version = "4.4.2" }
open = { version = "5.0.0" }

#tauri
tauri = { version = "1.4.0", features = [ "cli", "api-all"] }
tauri-plugin-window-state = { version = "^0.1" }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = [ "tauri/custom-protocol" ]
